Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "install_puppet.sh"
  config.vm.box = "bento/ubuntu-18.04"
  #config.puppet_install.puppet_version = :latest
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "./manifests"
    puppet.manifest_file = "default.pp"
  end
	
  config.vm.provider :digital_ocean do |provider, override|
	override.ssh.private_key_path = '~/.ssh/id_rsa'
	override.vm.box = 'digital_ocean'
	override.vm.box_url = "https://github.com/devopsgroup-io/vagrant-digitalocean/raw/master/box/digital_ocean.box"
	override.vm.allowed_synced_folder_types = :rsync
	 
	provider.token = ENV['DIGITALOCEAN-TOKEN']  # Remember to set the environment variable DIGITALOCEAN-TOKEN before running
	provider.image = 'ubuntu-18-04-x64'
	provider.region = 'nyc1'
	provider.size = 's-1vcpu-1gb'
    provider.setup = false
  end
  
  config.vm.provider :virtualbox do |vb|
    #vb.vm.box = "bento/ubuntu-18.04"
  end
  
	
  config.vm.define "appserver" do |appserver|
    appserver.vm.hostname = "appserver"
  end

  config.vm.define "dbserver" do |dbserver|
    dbserver.vm.hostname = "dbserver"
  end
end
